apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauronvisionprotocol
  labels:
    app: sauronvisionprotocol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sauronvisionprotocol
  template:
    metadata:
      labels:
        app: sauronvisionprotocol
    spec:
      containers:
      - name: sauronvisionprotocol
        image: __IMAGE__  # This will be replaced by GitHub Actions
        ports:
        - containerPort: 9000
          name: tcp-socket
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: PORT
          value: "9000"
        - name: ENVIRONMENT
          value: "Production"
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: acr-secret  # Secret for pulling from Azure Container Registry
